exports.deployZexCraft = require("../deploy/deployZexCraft.js")
exports.deployImplementation = require("../deploy/deployErc6551Implementation.js")
exports.deployRegistry = require("../deploy/deployErc6551Registry.js")
exports.deployTestingCCIPAutomation = require("../deploy/deployTestingCCIPAutomation.js")
exports.deployTestingCCIPReceiver = require("../deploy/deployTestingCCIPReceiver.js")
