exports.deployPegoCraft = require("../deploy/deployPegoCraft.js")
exports.deployImplementation = require("../deploy/deployErc6551Implementation.js")
exports.deployRegistry = require("../deploy/deployErc6551Registry.js")
exports.deployPowerups = require("./deployPowerups.js")
exports.deployRelationship = require("./deployRelationshipImplementation.js")
exports.deployRelationshipRegistry = require("./deployRelationshipRegistry.js")
exports.deployCraftToken = require("./deployCraftToken.js")
